# Generated by Django 2.2.2 on 2019-06-04 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
